# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.custom]
  command = "git clone https://github.com/opentargets/platform-app-customisations customisations && yarn build:customise"
  environment = { CUSTOMISATIONS_DIR = "customisations" }
